### ISSUE TITLE
verbose not defined globally

### ISSUE THREAD

**Issue by bastidererste** [robotics/open_abb#5]
abb.py 
line 34, in connect
if verbose: print 'Attempting to connect to ABB robot at', self.remote NameError: global name 'verbose' is not defined

temporary fix: initialize verbose at beginning with verbose = False

import socket, json, os, time
import threading
from collections import deque
--->verbose = False 

class Robot:
...

**Comment by mikedh** [comment]
This typo came in after a re-organization, let me know if there are any other issues. Thanks!
