### ISSUE TITLE
Does it work in virtual mode in robot studio 5.60 as well? 

### ISSUE THREAD

**Issue by bastidererste** [robotics/open_abb#6]
The Server.mod is throwing errors in the Socket creation section - wrong number of arguments - in robotstudio 5.60 RAPID editor...
Have you ever created a virtual irc5 robot with irc5 control and got it to work?

regards
basti

**Comment by mikedh** [comment]
I actually only have Robotstudio 5.15 here to test on, and I'll try to verify this works in a virtual there tomorrow. This version is a merge of 3-4 local branches, and we haven't tested this merged version as extensively as some of the branches. We have definitely had branches of this working in virtuals. Could you post the full error log? Also one possibility, did you change ipcontroller to either your machine's IP or 127.0.0.1?

Best,
Mike

**Comment by bastidererste** [comment]
If i know where to change the ipcontroller ;-) i would do that. Im a first time robotstudio user, so bare with me. What steps are between the simple creation of a station with a control and uploading the module to the (virtual) control? Do I have to configure anything on the control?
Error log is on the way...

Thank you for your time!!
basti

**Comment by bastidererste** [comment]
Got an interesting error... As the error log is in german i will translate it to you. The interesting error says: "Missing option(161): The instruction SocketCreate requires the option PC"
Now we are talking... where do I set the option PC?

basti

**Comment by albertor** [comment]
When you create the virtual controller, you need to add the option PC
Interface to it, so that socket communication is enabled.
You also need to enable multithreading.

Alberto.

**Comment by bastidererste** [comment]
Its exactly like that, Alberto. Just found it out with some help of abb forum: 
Create an empty station. In Home choose a robot from the ABB Library. Also in Home, click on Robot System and chose "from Layout". Follow the wizard till "options" appear. Choose PC interface from the Communication tree, and Multitasking from Engineering Tools tree (right below communication). Finish... And there you are!! issue solved!!

**Comment by albertor** [comment]
Glad to see that you found the way.

Alberto.
